on:
  push:
    branches: [ "main", "deploy" ]

env:
  USER: mingi4754song
  INSTANCE_NAME: server-instance
  ZONE: us-west1-b

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.20' ]

    steps:
      - name: Checkout from remote repository
        uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Display Go version
        run: go version

      - name: Build
        run: |
          go build -o run .

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Transfer to Google Cloud Compute Instance
        run: |
          gcloud compute scp ./run $USER@$INSTANCE_NAME:~/ --zone=$ZONE
